apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: application-web
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
      - name: mysql-deployment
        image: mariadb
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3306
        env:
          - name: MARIADB_ROOT_PASSWORD
            # value: "password"
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          - name: MARIADB_USER
            valueFrom:
              configMapKeyRef:
                name: mes-envs
                key: mysqluser
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: pvc-mysql
          
