apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: monapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: myapp
      labels:
        name: myapp
    spec:
      containers:
        - name: nginx
          image: nginx